# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WF_generator.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(358, 347)
        Form.setMaximumSize(QtCore.QSize(358, 347))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(346, 335))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.line_4 = QtWidgets.QFrame(self.frame_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Jokerman")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.edit_addVoltage = QtWidgets.QLineEdit(self.frame_3)
        self.edit_addVoltage.setObjectName("edit_addVoltage")
        self.horizontalLayout_6.addWidget(self.edit_addVoltage)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.edit_addFrame = QtWidgets.QLineEdit(self.frame_3)
        self.edit_addFrame.setObjectName("edit_addFrame")
        self.horizontalLayout_6.addWidget(self.edit_addFrame)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.pbtn_addVF = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        self.pbtn_addVF.setFont(font)
        self.pbtn_addVF.setObjectName("pbtn_addVF")
        self.verticalLayout.addWidget(self.pbtn_addVF)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.cbbx_voltage = QtWidgets.QComboBox(self.frame_3)
        self.cbbx_voltage.setObjectName("cbbx_voltage")
        self.horizontalLayout_5.addWidget(self.cbbx_voltage)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.cbbx_frame = QtWidgets.QComboBox(self.frame_3)
        self.cbbx_frame.setObjectName("cbbx_frame")
        self.horizontalLayout_5.addWidget(self.cbbx_frame)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.pbtn_add = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        self.pbtn_add.setFont(font)
        self.pbtn_add.setObjectName("pbtn_add")
        self.verticalLayout.addWidget(self.pbtn_add)
        self.pbtn_delete = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        self.pbtn_delete.setFont(font)
        self.pbtn_delete.setObjectName("pbtn_delete")
        self.verticalLayout.addWidget(self.pbtn_delete)
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.pbtn_copy = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        self.pbtn_copy.setFont(font)
        self.pbtn_copy.setObjectName("pbtn_copy")
        self.verticalLayout.addWidget(self.pbtn_copy)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.pbtn_export = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        self.pbtn_export.setFont(font)
        self.pbtn_export.setObjectName("pbtn_export")
        self.verticalLayout.addWidget(self.pbtn_export)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.frame)
        self.label.setBuddy(self.edit_addVoltage)
        self.label_2.setBuddy(self.edit_addFrame)
        self.label_3.setBuddy(self.cbbx_voltage)
        self.label_4.setBuddy(self.cbbx_frame)
        self.label_6.setBuddy(self.lineEdit_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pbtn_addVF, self.cbbx_voltage)
        Form.setTabOrder(self.cbbx_voltage, self.cbbx_frame)
        Form.setTabOrder(self.cbbx_frame, self.pbtn_add)
        Form.setTabOrder(self.pbtn_add, self.pbtn_delete)
        Form.setTabOrder(self.pbtn_delete, self.lineEdit_3)
        Form.setTabOrder(self.lineEdit_3, self.pbtn_copy)
        Form.setTabOrder(self.pbtn_copy, self.pbtn_export)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Add New Choice Here"))
        self.label.setText(_translate("Form", "add voltage"))
        self.label_2.setText(_translate("Form", "add frame #"))
        self.pbtn_addVF.setText(_translate("Form", "add voltage and frame to your choices"))
        self.label_3.setText(_translate("Form", "choose voltage:"))
        self.label_4.setText(_translate("Form", "choose frame #:"))
        self.pbtn_add.setText(_translate("Form", "add"))
        self.pbtn_delete.setText(_translate("Form", "delete"))
        self.label_6.setText(_translate("Form", "copy times"))
        self.pbtn_copy.setText(_translate("Form", "copy"))
        self.pbtn_export.setText(_translate("Form", "export"))


